create table admin_user (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), id varchar(30) not null, name varchar(10) not null, password varchar(64) not null, primary key (idx)) engine=InnoDB;
create table climbing_place (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), location varchar(200) not null, name varchar(50) not null, status enum ('ACTIVATED','DEACTIVATED','DELETED') default 'ACTIVATED', primary key (idx)) engine=InnoDB;
create table climbing_schedule (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), end_date_time DATETIME(6) not null, start_date_time DATETIME(6) not null, climbing_place_idx integer, primary key (idx)) engine=InnoDB;
create table climbing_schedule_participant (created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), member_idx integer not null, climbing_schedule_idx integer not null, primary key (climbing_schedule_idx, member_idx)) engine=InnoDB;
create table club_membership_fee (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), memo TEXT not null, price integer not null, primary key (idx)) engine=InnoDB;
create table club_membership_fee_payer (created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), is_paid TINYINT(1) not null, memo TEXT not null, paid_date_time DATETIME(6) not null, club_membership_fee_idx integer not null, member_idx integer not null, primary key (club_membership_fee_idx, member_idx)) engine=InnoDB;
create table club_membership_fee_usage (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), memo TEXT, price integer not null, usage_date DATETIME(6) not null, primary key (idx)) engine=InnoDB;
create table club_membership_fee_usage_member (created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), member_idx integer not null, club_membership_fee_usage_idx integer not null, primary key (club_membership_fee_usage_idx, member_idx)) engine=InnoDB;
create table member (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), birth date not null, gender enum ('MALE','FEMALE') not null, name varchar(10) not null, status enum ('ACTIVATED','DEACTIVATED','DELETED') default 'ACTIVATED', primary key (idx)) engine=InnoDB;
create table member_detail (idx integer not null auto_increment, created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL, modified_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6), career integer not null, etc_info TEXT, is_injured TINYINT(1) DEFAULT 0 not null, is_introduced_self TINYINT(1) DEFAULT 0 not null, is_joined_chat TINYINT(1) DEFAULT 0 not null, member_idx integer, primary key (idx)) engine=InnoDB;

-- Set foreign key index & unique index
# alter table admin_user drop index UK_7nkel3co8kr1vfjyx1yojmytk; (불필요한 쿼리)
alter table admin_user add constraint UK_7nkel3co8kr1vfjyx1yojmytk unique (id);
alter table climbing_schedule add constraint FKn3lt4mhte7hepd18j0fgaiquu foreign key (climbing_place_idx) references climbing_place (idx);
alter table climbing_schedule_participant add constraint FKawotrwb71a0rfun6amlbsdh1 foreign key (member_idx) references member (idx);
alter table climbing_schedule_participant add constraint FK1js0jr1nkef6l1bvr5kouqxwh foreign key (climbing_schedule_idx) references climbing_schedule (idx);
alter table club_membership_fee_payer add constraint FKbmgkojjwrd60dt612qw61ieid foreign key (club_membership_fee_idx) references club_membership_fee (idx);
alter table club_membership_fee_payer add constraint FK9f5xf9pfedxc22bnbpx38knfr foreign key (member_idx) references member (idx);
alter table club_membership_fee_usage_member add constraint FK1y5ncpvc9t2pjavbdw7okbsyt foreign key (member_idx) references member (idx);
alter table club_membership_fee_usage_member add constraint FKl9gtee0m2jvaixpquw4hdm9fa foreign key (club_membership_fee_usage_idx) references club_membership_fee_usage (idx);
alter table member_detail add constraint FK2vlbin68bvxl0ne4mhryeup1b foreign key (member_idx) references member (idx);